version: '3'

services:
  app:
    container_name: schedule-queue
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:6.2.6-alpine3.14
